export enum RoleValue {
    GLOBAL_ADMIN = 'GLOBAL_ADMIN',
    ORGANISATION_ADMIN = 'ADMIN',
    PROJECT_ADMIN = 'PROJECT_ADMIN',

    ORGANISATION_WORKER = 'ORGANISATION_WORKER',
    PROJECT_WORKER = 'PROJECT_WORKER',

    USER = "USER"
}
  